# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "src/requirements.txt"
        
      - name: validate the format 
        run: |
          echo 'validate the format'
          python src/test.py 
          
      - name: install tidy 
        run: |
          echo 'install tidy'
          npm install -g bibtex-tidy@1.11.0
          
      - name: tidy up!  
        run: |
          echo 'tidy up!'
          bibtex-tidy --tab --align=13  --remove-dupe-fields  --numeric  --trailing-commas   --sort-fields=title,shorttitle,author,year,month,day,journal,booktitle,location,on,publisher,address,series,volume,number,pages,doi,isbn,issn,url,urldate,copyright,category,note,metadata  --sort=year,booktitle,journal,title,author,key  --curly --duplicates  ref.bib

      - name: git status
        run: |
          git status

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          add: '*.bib'

          # The name of the user that will be displayed as the author of the commit.
          author_name: github

          # The email of the user that will be displayed as the author of the commit.
          author_email: danyal.khashabi@gmail.com


          # The name of the custom committer you want to use, if different from the author of the commit.
          committer_name: 🤖

          # The email of the custom committer you want to use, if different from the author of the commit.
          committer_email: danyal.khashabi@gmail.com

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actor

          # The message for the commit.
          message: 'automated commit after tidying up! 🤖🤖🤖'
